[2022-10-27T14:01:53.135+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:01:47.069341+00:00 [queued]>
[2022-10-27T14:01:53.199+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T14:01:47.069341+00:00 [queued]>
[2022-10-27T14:01:53.199+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:01:53.199+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-27T14:01:53.199+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:01:53.278+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 14:01:47.069341+00:00
[2022-10-27T14:01:53.318+0000] {standard_task_runner.py:54} INFO - Started process 231 to run task
[2022-10-27T14:01:53.323+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T14:01:47.069341+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpqo6jnylj']
[2022-10-27T14:01:53.325+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask processing_data
[2022-10-27T14:01:53.352+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T14:02:01.080+0000] {local_task_job.py:87} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-27T14:02:01.853+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 231. PIDs of all processes in the group: [231]
[2022-10-27T14:02:01.853+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 231
[2022-10-27T14:02:03.711+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=231, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='14:01:52') (231) terminated with exit code Negsignal.SIGTERM
[2022-10-27T14:02:03.712+0000] {local_task_job.py:164} INFO - Task exited with return code 143
[2022-10-27T14:02:04.138+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
