[2022-10-27T14:01:53.140+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.training_and_retraining_the_model.retraining_model manual__2022-10-27T14:01:47.069341+00:00 [queued]>
[2022-10-27T14:01:53.204+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.training_and_retraining_the_model.retraining_model manual__2022-10-27T14:01:47.069341+00:00 [queued]>
[2022-10-27T14:01:53.205+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:01:53.205+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-27T14:01:53.205+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T14:01:53.299+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): training_and_retraining_the_model.retraining_model> on 2022-10-27 14:01:47.069341+00:00
[2022-10-27T14:01:53.339+0000] {standard_task_runner.py:54} INFO - Started process 232 to run task
[2022-10-27T14:01:53.347+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'training_and_retraining_the_model.retraining_model', 'manual__2022-10-27T14:01:47.069341+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpp5vkejwc']
[2022-10-27T14:01:53.371+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask training_and_retraining_the_model.retraining_model
[2022-10-27T14:01:53.372+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T14:02:01.080+0000] {local_task_job.py:87} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-27T14:02:01.200+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 232. PIDs of all processes in the group: [232]
[2022-10-27T14:02:01.200+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 232
[2022-10-27T14:02:03.378+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=232, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='14:01:53') (232) terminated with exit code Negsignal.SIGTERM
[2022-10-27T14:02:03.379+0000] {local_task_job.py:164} INFO - Task exited with return code 143
[2022-10-27T14:02:03.647+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
