[2022-10-27T15:05:07.832+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T15:04:57.310274+00:00 [queued]>
[2022-10-27T15:05:08.370+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ml_pipeline.processing_data manual__2022-10-27T15:04:57.310274+00:00 [queued]>
[2022-10-27T15:05:08.371+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T15:05:08.371+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-27T15:05:08.371+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T15:05:08.720+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): processing_data> on 2022-10-27 15:04:57.310274+00:00
[2022-10-27T15:05:08.818+0000] {standard_task_runner.py:54} INFO - Started process 203 to run task
[2022-10-27T15:05:08.873+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'processing_data', 'manual__2022-10-27T15:04:57.310274+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpuli8u5a5']
[2022-10-27T15:05:08.938+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask processing_data
[2022-10-27T15:05:08.994+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_pipeline.py
[2022-10-27T15:05:15.610+0000] {local_task_job.py:87} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-27T15:05:15.612+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 203. PIDs of all processes in the group: [203]
[2022-10-27T15:05:15.612+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 203
[2022-10-27T15:05:17.682+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=203, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='15:05:08') (203) terminated with exit code Negsignal.SIGTERM
[2022-10-27T15:05:17.682+0000] {local_task_job.py:164} INFO - Task exited with return code 143
[2022-10-27T15:05:18.295+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
